# Generated by Django 2.1 on 2018-08-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=50, verbose_name='Barrio')),
                ('calle', models.CharField(max_length=50)),
                ('piso', models.CharField(max_length=50)),
                ('ambientes', models.IntegerField(default=0)),
                ('superficie_cubierta', models.IntegerField(default=0)),
                ('superficie_descubierta', models.IntegerField(default=0)),
                ('operacion', models.CharField(choices=[('V', 'Venta'), ('A', 'Alquiler')], max_length=50)),
                ('tipo', models.CharField(choices=[('C', 'Casa'), ('D', 'Departameto'), ('T', 'Terreno'), ('G', 'Garage'), ('P', 'PH'), ('O', 'Oficina')], max_length=50)),
                ('antiguedad', models.CharField(choices=[('E', 'A Estrenar'), ('D', 'Mas de 10 Años'), ('V', 'Mas de 20 Años'), ('T', 'Mas de 30 Años')], max_length=50)),
                ('descripcion', models.CharField(max_length=1000)),
                ('precio', models.IntegerField()),
                ('expensas', models.IntegerField()),
                ('width_modified', models.IntegerField(default=0)),
                ('height_modified', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
            },
        ),
        migrations.CreateModel(
            name='PropiedadImagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('property', models.ForeignKey(on_delete='cascade', related_name='images', to='propiedades.Propiedad')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='propiedad',
            field=models.ForeignKey(blank=True, null=True, on_delete='cascade', to='propiedades.Propiedad'),
        ),
    ]
